
export const GRATICULE_DEFAULTS = {
  DISPLAY_BACKGROUND: true,
  DISPLAY_LINES: true,
  DISPLAY_BORDERS: true,
  BORDERS_COLOR: '#000000',
  BORDERS_WIDTH: '1px',
  BACKGROUND_COLOR: '#a4bac7',
  LINES_COLOR: '#888888',
  LINES_WIDTH: '0.5px',
  LINES_OPACITY: '0.5'
};

export const GEODATA_DEFAULTS = {
  BACKGROUND_COLOR: '#ffffff',
  LINES_COLOR: '#000000',
  LINES_WIDTH: '0.5px',
  LINES_OPACITY: '0.5'
};

export const SHAPE_CIRCLE_DEFAULTS = {
  BACKGROUND_OPACITY: '0.75',
  BACKGROUND_COLOR: '#ffffff',
  LINES_COLOR: '#000000',
  LINES_WIDTH: '0.5px',
  LINES_OPACITY: '0.5'
};

export const SHAPE_POINT_DEFAULTS = {
  BACKGROUND_OPACITY: '0.75',
  BACKGROUND_COLOR: '#ffffff',
  LINES_COLOR: '#000000',
  LINES_WIDTH: '0.5px',
  LINES_OPACITY: '0.5'
};